//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerList
    {
        public string MsDN { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string Diachi { get; set; }
        public string Mst { get; set; }
        public string Nguoimua { get; set; }
        public string Dienthoai { get; set; }
        public string Email { get; set; }
        public string Stk { get; set; }
        public string TaiNH { get; set; }
        public decimal Sdphaithu { get; set; }
        public decimal Sdphaitra { get; set; }
        public string Ghichu { get; set; }
    }
}
