//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DulieuHoadon
    {
        public string MsDn { get; set; }
        public string Mauso { get; set; }
        public string Kyhieu { get; set; }
        public decimal Sohoadon { get; set; }
        public string Mabaomat { get; set; }
        public System.DateTime Ngayhoadon { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string MstKH { get; set; }
        public string Diachi { get; set; }
        public string Hotennguoimua { get; set; }
        public string Sotaikhoan { get; set; }
        public string TaiNganhang { get; set; }
        public string SdtKH { get; set; }
        public string EmailKH { get; set; }
        public string HTthanhtoan { get; set; }
        public string Mahang { get; set; }
        public string Tenhang { get; set; }
        public string Dvt { get; set; }
        public decimal Soluong { get; set; }
        public decimal Dongia { get; set; }
        public decimal Thanhtien { get; set; }
        public string Thuesuat { get; set; }
        public decimal TienthueGTGT { get; set; }
        public int TyleCK { get; set; }
        public decimal TienChietkhau { get; set; }
        public string HoadonThaythe { get; set; }
        public string HoadonDieuchinh { get; set; }
        public string HoadonHuy { get; set; }
        public string HoadonChuyendoi { get; set; }
        public string NgayTTDCCD { get; set; }
        public string Tinhtrang { get; set; }
        public string Lydo { get; set; }
        public string Chinhanh { get; set; }
        public string Ghichu { get; set; }
        public decimal KHTra { get; set; }
        public decimal TraNCC { get; set; }
        public string Diengiai { get; set; }
        public string TkNo { get; set; }
        public string TkCo { get; set; }
        public decimal SLNhap { get; set; }
        public decimal DGNhap { get; set; }
        public decimal TTNhap { get; set; }
        public decimal TienthueNhap { get; set; }
        public string Nhanvien { get; set; }
    }
}
