//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public string Mst { get; set; }
        public string EmailNguoinhan { get; set; }
        public string Cc { get; set; }
        public string DuongdanFile { get; set; }
        public string TenFile { get; set; }
        public string Tieude { get; set; }
        public string Noidung { get; set; }
        public string Ghichu { get; set; }
    }
}
