//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailDangky
    {
        public string Mst { get; set; }
        public string EmailGui { get; set; }
        public string MatKhau { get; set; }
        public string smtpServerPort { get; set; }
        public string smtpServerHost { get; set; }
        public string Ghichu { get; set; }
    }
}
