//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodServicesList
    {
        public string MsDN { get; set; }
        public string MaHHDV { get; set; }
        public string TenHHDV { get; set; }
        public string Dvt { get; set; }
        public double Dongiamua { get; set; }
        public double Dongiaban { get; set; }
        public double Sldk { get; set; }
        public decimal TTdk { get; set; }
        public int Tyleck { get; set; }
        public string Baohanh { get; set; }
        public string Ghichu { get; set; }
    }
}
