//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichsuTBPH
    {
        public string MsDn { get; set; }
        public string MaloaiHD { get; set; }
        public string TenloaiHD { get; set; }
        public string Mauso { get; set; }
        public string Kyhieu { get; set; }
        public decimal Soluong { get; set; }
        public decimal Tuso { get; set; }
        public decimal Denso { get; set; }
        public System.DateTime NgaybatdauSD { get; set; }
        public string TenDN { get; set; }
        public string Mst { get; set; }
        public string TenDVCQ { get; set; }
        public string MstDVCQ { get; set; }
        public string TenCQThue { get; set; }
        public System.DateTime NgayTBPH { get; set; }
        public string NguoiDDPL { get; set; }
    }
}
