//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LookupInvoice.Domain.Infrastructure.Abstract;

namespace LookupInvoice.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext, IDbFactory
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerList> CustomerLists { get; set; }
        public virtual DbSet<DanhmucNCC> DanhmucNCCs { get; set; }
        public virtual DbSet<EmailDangky> EmailDangkies { get; set; }
        public virtual DbSet<GoodServicesList> GoodServicesLists { get; set; }
        public virtual DbSet<LoiChuaDongBoFTP> LoiChuaDongBoFTPs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Chuaky> Chuakies { get; set; }
        public virtual DbSet<DulieuHoadon> DulieuHoadons { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<LichsuTBPH> LichsuTBPHs { get; set; }
        public virtual DbSet<Nhatkynhapkho> Nhatkynhapkhoes { get; set; }
        public virtual DbSet<Nhatkythu> Nhatkythus { get; set; }
        public virtual DbSet<PathFile> PathFiles { get; set; }
        public virtual DbSet<RESETHoadon> RESETHoadons { get; set; }
        public virtual DbSet<SyncInvoice> SyncInvoices { get; set; }
        public virtual DbSet<TaikhoanDN> TaikhoanDNs { get; set; }
    }
}
