//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhatkythu
    {
        public string Kyhieu { get; set; }
        public decimal Sohoadon { get; set; }
        public System.DateTime Ngaythu { get; set; }
        public string Httt { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string Diengiai { get; set; }
        public decimal Sotienthu { get; set; }
        public string Ghichu { get; set; }
    }
}
