//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhatkynhapkho
    {
        public string Kyhieu { get; set; }
        public decimal Sohoadon { get; set; }
        public System.DateTime Ngay { get; set; }
        public string Httt { get; set; }
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string Mahang { get; set; }
        public string Tenhang { get; set; }
        public string Dvt { get; set; }
        public decimal SLNhap { get; set; }
        public decimal DGNhap { get; set; }
        public decimal TTNhap { get; set; }
        public string Diengiai { get; set; }
        public decimal SotientraNCC { get; set; }
        public string Ghichu { get; set; }
    
        public virtual DanhmucNCC DanhmucNCC { get; set; }
    }
}
