//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PathFile
    {
        public string Mst { get; set; }
        public string Kyhieu { get; set; }
        public decimal Sohoadon { get; set; }
        public System.DateTime Ngayhoadon { get; set; }
        public string Duongdan { get; set; }
        public string Tenfile { get; set; }
        public string Tenforder { get; set; }
        public string Ghichu { get; set; }
        public string Kiemtra { get; set; }
    }
}
