//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESETHoadon
    {
        public string Mst { get; set; }
        public string KyHieu { get; set; }
        public string SoHD { get; set; }
        public System.DateTime Ngay { get; set; }
        public string TenFile { get; set; }
        public string DuongdanFile { get; set; }
        public string Ghichu { get; set; }
    }
}
