//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupInvoice.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaikhoanDN
    {
        public int Stt { get; set; }
        public string Masothue { get; set; }
        public string Matkhau { get; set; }
        public string TenDN { get; set; }
        public string SoHopDong { get; set; }
        public System.DateTime NgayKy { get; set; }
        public string GoiHoaDon { get; set; }
        public string KyHieu { get; set; }
        public string GhiChu { get; set; }
    }
}
